export BOOT_DEBUG_VERSION=0
export UI_HAVE_LOGO=1
export ENABLE_AVMUTE_CONTROL=1
export ENABLE_AUTO_BACKLIGHT_CONTROL=0

export PQ_BINARY_START=0xF5000
export PQ_BINARY_UNIT_SIZE=0x4000

export FBC_USER_START=0x1FE000
export FBC_USER_SIZE=0x2000

export USER_HDCPKEY=$FBC_USER_START
export USER_HDCPKEY_SIZE=0x400

export USER_SETTING_START=$USER_HDCPKEY+$USER_HDCPKEY_SIZE
export USER_SETTING_SIZE=0x100

export USER_WB_SETTING_START=$USER_SETTING_START+$USER_SETTING_SIZE
export USER_WB_SETTING_SIZE=0x100

export USER_PIC_SETTING_START=$USER_WB_SETTING_START+$USER_WB_SETTING_SIZE
export USER_PIC_SETTING_SIZE=0x100

export USER_CRI_DATA_SIZE=0x400
export USER_CRI_DATA_START=$FBC_USER_START+$FBC_USER_SIZE-$USER_CRI_DATA_SIZE
